
name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * *"   # run daily at 00:00 UTC
  workflow_dispatch: {}

permissions:
  contents: write   # allow commits/pushes from this workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.PROFILE_SUMMARY_CARDS_TOKEN }}
        with:
          USERNAME: eaziey
          BRANCH_NAME: main         
          UTC_OFFSET: 2 
          AUTO_PUSH: true
          # EXCLUDE: "JavaScript,HTML"  # optional: exclude languages
